name: Code Styling Check
on:
  push:
    paths-ignore:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - '**/README.*'
      - CONTRIBUTING.md
      - CODING_STANDARDS.md
      - .cirrus.yml
      - .travis.yml
      - travis/*
      - .circleci/*
    branches:
      - PHP-8.1
      - PHP-8.2
      - PHP-8.3
      - master
  pull_request:
    paths-ignore:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - '**/README.*'
      - CONTRIBUTING.md
      - CODING_STANDARDS.md
      - .cirrus.yml
      - .travis.yml
      - travis/*
      - .circleci/*
    branches:
      - '**'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.url || github.run_id }}
  cancel-in-progress: true
jobs:
  CODE_FORMATTING_CHECK:
    name: Code formatting check
#    if: github.repository_owner == 'php' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install \
            git \
            clang-format \
            php-cli \
            netcat-openbsd
      - name: Check code formatting
        run: |
          set -x
          echo "foobar" > format.patch
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: 'format.patch'
          path: format.patch
          if-no-files-found: ignore
      - name: 'Show summary'
        run: |
          echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
          echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
          cat 'Run curl ${{ steps.artifact-upload-step.outputs.artifact-url }} | git patch apply' > $GITHUB_STEP_SUMMARY
