name: Code Styling Check
on:
  push:
    paths-ignore:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - '**/README.*'
      - CONTRIBUTING.md
      - CODING_STANDARDS.md
      - .cirrus.yml
      - .travis.yml
      - travis/*
      - .circleci/*
    branches:
      - PHP-8.1
      - PHP-8.2
      - PHP-8.3
      - master
  pull_request:
    paths-ignore:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - '**/README.*'
      - CONTRIBUTING.md
      - CODING_STANDARDS.md
      - .cirrus.yml
      - .travis.yml
      - travis/*
      - .circleci/*
    branches:
      - '**'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.url || github.run_id }}
  cancel-in-progress: true
jobs:
  CODE_FORMATTING_CHECK:
    name: CODE_FORMATTING_CHECK
#    if: github.repository_owner == 'php' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: apt
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install \
            git \
            clang-format \
            php-cli \
            netcat-openbsd
      - name: check code formatting
        run: |
          set -x
          git fetch origin master
          git diff origin/master > ../master.diff
          if [ -f scripts/dev/format_pull_request.php ]; then
            cp scripts/dev/format_pull_request.php ..
          fi
          git checkout master
          if [ -f scripts/dev/format_pull_request.php ]; then
            cp scripts/dev/format_pull_request.php ..
          fi
          if [ ! -f ../format_pull_request.php ]; then
            echo "error: format_pull_request.php does not exist" 1>&2
            exit 1
          fi
          git reset --hard origin/master
          php ../format_pull_request.php ../master.diff > ../formatted.diff
          if [ -s ../formatted.diff ]; then
            cat ../formatted.diff
            echo "code formatting check failed :("
            patch_url=$(cat ../formatted.diff | nc termbin.com 9999)
            echo "Please run"
            echo "curl $patch_url | git apply -v"
            exit 1
          else
            echo "code formatting check succeeded :)"
            exit 0
          fi
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: 'format.patch'
          path: ../formatted.diff
